image: mambaorg/micromamba:1.5.6-jammy

build and test:
  cache:
    paths:
      - micromamba
  before_script:
    - mkdir -p micromamba
    - export MAMBA_ROOT_PREFIX=micromamba
    - micromamba create -yf environment.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate mumps
  script:
    - spin test

pre-commit:
  cache:
    paths:
      - .pre-commit-cache
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.pre-commit-cache
  before_script:
    - micromamba install -y -c conda-forge pre-commit git
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pre-commit run --all-files
