image: gitlab.kwant-project.org:5005/kwant/testing

stages:
  - build
  - test


.build: &build
  stage: build
  script:
    - echo -e "[DEFAULT]\ndefine_macros = CYTHON_TRACE=1" >> build.conf
    - ./setup.py build
    - ./setup.py build_ext -i
  artifacts:
    untracked: true
    expire_in: 1 hour

# Note that this is 'latest' as of when the image was last built
.latest-env: &latest_env
  before_script:
    - source deactivate
    - source activate kwant-latest
    - conda install jinja2
    - ci/generate-conda-build-config
    - unset CFLAGS  # https://github.com/conda-forge/toolchain-feedstock/issues/41

.ubuntu-env: &ubuntu_env
  image: gitlab.kwant-project.org:5005/kwant/testing/ubuntu
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends python3-jinja2

.debian-env: &debian_env
  image: gitlab.kwant-project.org:5005/kwant/testing/debian
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends python3-jinja2


## Build Jobs

build:ubuntu:
  <<: *build
  <<: *ubuntu_env

build:debian:
  <<: *build
  <<: *debian_env

build:latest:
  <<: *build
  <<: *latest_env

## Test Jobs

check whitespace style:
  stage: test
  script: ci/check_whitespace
  allow_failure: true

.test: &test
  stage: test
  script:
    - py.test -r w --flakes mumpy

test:ubuntu:
  <<: *test
  <<: *ubuntu_env
  dependencies:
    - build:ubuntu

test:debian:
  <<: *test
  <<: *debian_env
  dependencies:
    - build:debian

test:latest:
  <<: *test
  <<: *latest_env
  dependencies:
    - build:latest
