#!/bin/bash

if [[ -z "$CONDA_PREFIX" ]]; then
    echo "no Conda environment active"
    exit 1
fi

cat <<EOF >build.conf
[mumps]
include_dirs = $CONDA_PREFIX/include
library_dirs = $CONDA_PREFIX/lib
libraries = smumps dmumps cmumps zmumps mumps_common pord metis esmumps scotch scotcherr mpiseq blas gfortran
extra_link_args = -Wl,-rpath=$CONDA_PREFIX/lib
EOF
